project_id = "lqpdvleqamdsicsisfeg"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-template]
verify_jwt = false

[functions.leaderboard]
verify_jwt = false

[functions.image-pro]
verify_jwt = false

[functions.video-pro]
verify_jwt = false

[functions.analyze-website]
verify_jwt = false
